export const Columns = [
  {
    title: 'Contrato',
    accessor: 'contract',
  },
  {
    title: 'Plano',
    accessor: 'plan',
  },
  {
    title: 'Valor',
    accessor: 'price',
  },
  {
    title: 'Situação',
    accessor: 'subject',
  },
  {
    title: 'Início',
    accessor: 'initial_date',
  },
  {
    title: 'Fim',
    accessor: 'end_date',
    isNumeric: true,
  },
];

export const dataFake = [
  {
    contract: '#0003',
    initial_date: '30/10/2020',
    end_date: '30/10/2020',
    subject: 'Cancelamento',
    plan: 'Just Recupera',
    price: 'R$ 93,78',
    actions: 'cancelamento',
    more: [
      {
        parcela: 'Anuidade plano recorrente - 2020 - Parcela única',
        plano: '',
        valor: '94,99',
        situacao: 'Cancelado',
        resp: '10/2019',
        data: '10/290',
        nada: '',
        nada2: '',
      },
      {
        parcela: 'Anuidade plano recorrente - 2020 - Parcela única',
        plano: '',
        valor: '94,99',
        situacao: 'Cancelado',
        resp: '10/2019',
        data: '10/290',
        nada: '',
        nada2: '',
      },
      {
        parcela: 'Anuidade plano recorrente - 2020 - Parcela única',
        plano: '',
        valor: '94,99',
        situacao: 'Cancelado',
        resp: '10/2019',
        data: '10/290',
        nada: '',
        nada2: '',
      },
      {
        parcela: 'Anuidade plano recorrente - 2020 - Parcela única',
        plano: '',
        valor: '94,99',
        situacao: 'Cancelado',
        resp: '10/2019',
        data: '10/290',
        nada: '',
        nada2: '',
      },
      {
        parcela: 'Anuidade plano recorrente - 2020 - Parcela única',
        plano: '',
        valor: '94,99',
        situacao: 'Cancelado',
        resp: '10/2019',
        data: '10/290',
        nada: '',
        nada2: '',
      },
    ],
  },
  {
    contract: '#0003',
    initial_date: '30/10/2020',
    end_date: '30/10/2020',
    subject: 'Cancelamento',
    plan: 'Just Recupera',
    price: 'R$ 93,78',
    actions: 'cancelamento',
    more: [
      {
        parcela: 'Anuidade plano recorrente - 2020 - Parcela única',
        plano: '',
        valor: '94,99',
        situacao: 'Cancelado',
        resp: '10/2019',
        data: '10/290',
        nada: '',
        nada2: '',
      },
    ],
  },
  {
    contract: '#0003',
    initial_date: '30/10/2020',
    end_date: '30/10/2020',
    subject: 'Cancelamento',
    plan: 'Just Recupera',
    price: 'R$ 93,78',
    actions: 'cancelamento',
    more: [
      {
        parcela: 'Anuidade plano recorrente - 2020 - Parcela única',
        plano: '',
        valor: '94,99',
        situacao: 'Cancelado',
        resp: '10/2019',
        data: '10/290',
        nada: '',
        nada2: '',
      },
    ],
  },
];
